# Generated by Django 2.2.16 on 2020-10-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('job_type', models.CharField(choices=[('Architecture and Engineering Occupations', 'Architecture and Engineering Occupations'), ('Arts, Design, Entertainment, Sports, and Media Occupations', 'Arts, Design, Entertainment, Sports, and Media Occupations'), ('Building and Grounds Cleaning and Maintenance Occupations', 'Building and Grounds Cleaning and Maintenance Occupations'), ('Business and Financial Operations Occupations', 'Business and Financial Operations Occupations'), ('Community and Social Services Occupations', 'Community and Social Services Occupations'), ('Computer and Mathematical Occupations', 'Computer and Mathematical Occupations'), ('Construction and Extraction Occupations', 'Construction and Extraction Occupations'), ('Education, Training, and Library Occupations', 'Education, Training, and Library Occupations'), ('Farming, Fishing, and Forestry Occupations', 'Farming, Fishing, and Forestry Occupations'), ('Food Preparation and Serving Related Occupations', 'Food Preparation and Serving Related Occupations'), ('Healthcare Practitioners and Technical Occupations', 'Healthcare Practitioners and Technical Occupations'), ('Healthcare Support Occupations', 'Healthcare Support Occupations'), ('Installation, Maintenance, and Repair Occupations', 'Installation, Maintenance, and Repair Occupations'), ('Legal Occupations', 'Legal Occupations'), ('Life, Physical, and Social Science Occupations', 'Life, Physical, and Social Science Occupations'), ('Management Occupations', 'Management Occupations')], default='Other', max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=70)),
                ('vacancy', models.CharField(max_length=20)),
                ('salary', models.FloatField(default=0.0)),
                ('experiance', models.CharField(max_length=50)),
                ('publishedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
