# Generated by Django 2.2.16 on 2020-10-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='gender',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to='imageJobs/'),
            preserve_default=False,
        ),
    ]
