# Generated by Django 2.2.16 on 2020-10-16 10:56

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201016_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to=jobs.models.image_upload),
        ),
    ]
